[project]
name = "studio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.11",
    "jose>=1.0.0",
    "passlib>=1.7.4",
    "psycopg2>=2.9.10",
]

[dependency-groups]
dev = [
    "ruff>=0.9.10",
]
